stages:
  - build
  - deploy

variables:
  LC_ALL: en_US.UTF-8
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

pages:
  stage: build
  tags:
    - courseweb
  image: python:3.13
  before_script:
    - python3 -m venv env
    - source env/bin/activate
    - pip install -r requirements.txt
  script:
    - jupyter-book build --html
  artifacts:
    paths:
      - _build

courseweb:
  stage: deploy
  tags:
    - courseweb
  script:
    - /www/utils/deploycourseweb.sh
  cache: {}
  variables:
    course: cse163
    quarter: 25au
    source_path: _build/html
    delete: 'yes' # https://yaml.org/type/bool.html
    GIT_STRATEGY: none
  only:
    - main
  dependencies:
    - pages
