stages:
  - build
  - deploy

variables:
  LC_ALL: en_US.UTF-8

jupyter-book:
  stage: build
  tags:
    - pages
  image: node:18
  before_script:
    - npm install -g jupyter-book
  script:
    - jupyter-book build --html
  artifacts:
    paths:
      - _build/html

courseweb:
  stage: deploy
  tags:
    - courseweb
  script:
    - /www/utils/deploycourseweb.sh
  cache: {}
  variables:
    course: cse163
    quarter: 25au
    source_path: _build/html
    delete: 'yes' # https://yaml.org/type/bool.html
    GIT_STRATEGY: none
  only:
    - main
  dependencies:
    - jupyter-book
